version: "3.7"
name: studentjob-tfg
services:
  mysql:
    image: "mysql:5.7"
    container_name: studentjob-mysql
    networks:
      - studentjob-network
    ports:
      - 33061:3306
    environment:
      - LCP_PROJECT_ENVIRONMENT=dockerpre
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lportal
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  liferay:
    build: ./build/docker
    #image: studentjob-uoc-liferay:7.4.3.49-ga49
    container_name: studentjob-liferay
    environment:
      - LCP_PROJECT_ENVIRONMENT=docker-pre
      - LIFERAY_JAVA_OPTS=-Xms2g -Xmx2g
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE= true
      - LIFERAY_REDIRECT_PERIOD_URL_PERIOD_SECURITY_PERIOD_MODE= domain
    ports:
      - "127.0.0.1:11312:11311"
      - "127.0.0.1:8085:8080"
      - "127.0.0.1:9000:9000"
    volumes:
      - type: volume
        source: liferay-data
        target: /opt/liferay/data
      - type: bind
        source: build/docker/deploy
        target: /opt/liferay/deploy
      - type: bind
        source: bundles/deploy
        target: /opt/liferay/deploy
    networks:
      - studentjob-network
    depends_on:
      mysql:
        condition: service_healthy
  search:
    image: "liferaycloud/elasticsearch:6.8.4-3.0.5"
    container_name: studentjob-elastic
    environment:
      - LCP_PROJECT_ENVIRONMENT=local
      - LCP_SERVICE_SCALE=1
      - LCP_SERVICE_ID=search
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    networks:
      - studentjob-network
    volumes:
      - elastisearch-data:/usr/share/elasticsearch/data

networks:
  studentjob-network:
    name: studentjob-network

volumes:
  liferay-data:
  database-data:
  elastisearch-data: