version: "3.7"
name: studentjob
services:
  mysql:
    image: "mysql:5.7"
    container_name: studentjob-mysql-tfg
    networks:
      - studentjob-network-tfg
    ports:
      - 33061:3306
    environment:
      - LCP_PROJECT_ENVIRONMENT=dockerpre
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=studentportal
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    volumes:
      - type: volume
        source: database-data-tfg
        target: /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  studentjob-network-tfg:
    name: studentjob-network-tfg

volumes:
  database-data-tfg: