/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.uoc.mestemi.studentjob.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import edu.uoc.mestemi.studentjob.model.SocialMediaNetwork;
import edu.uoc.mestemi.studentjob.model.SocialMediaNetworkModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SocialMediaNetwork service. Represents a row in the &quot;SJob_SocialMediaNetwork&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SocialMediaNetworkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SocialMediaNetworkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SocialMediaNetworkImpl
 * @generated
 */
@JSON(strict = true)
public class SocialMediaNetworkModelImpl
	extends BaseModelImpl<SocialMediaNetwork>
	implements SocialMediaNetworkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a social media network model instance should use the <code>SocialMediaNetwork</code> interface instead.
	 */
	public static final String TABLE_NAME = "SJob_SocialMediaNetwork";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"socialMediaNetworkId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"logo", Types.BIGINT},
		{"baseURL", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("socialMediaNetworkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("logo", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("baseURL", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SJob_SocialMediaNetwork (uuid_ VARCHAR(75) null,socialMediaNetworkId LONG not null primary key,groupId LONG,companyId LONG,name VARCHAR(75) null,logo LONG,baseURL VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table SJob_SocialMediaNetwork";

	public static final String ORDER_BY_JPQL =
		" ORDER BY socialMediaNetwork.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SJob_SocialMediaNetwork.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SocialMediaNetworkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _socialMediaNetworkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSocialMediaNetworkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _socialMediaNetworkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SocialMediaNetwork.class;
	}

	@Override
	public String getModelClassName() {
		return SocialMediaNetwork.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SocialMediaNetwork, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SocialMediaNetwork, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SocialMediaNetwork, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SocialMediaNetwork)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SocialMediaNetwork, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SocialMediaNetwork, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SocialMediaNetwork)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SocialMediaNetwork, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SocialMediaNetwork, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SocialMediaNetwork, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SocialMediaNetwork, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SocialMediaNetwork, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SocialMediaNetwork, Object>>();
		Map<String, BiConsumer<SocialMediaNetwork, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SocialMediaNetwork, ?>>();

		attributeGetterFunctions.put("uuid", SocialMediaNetwork::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<SocialMediaNetwork, String>)
				SocialMediaNetwork::setUuid);
		attributeGetterFunctions.put(
			"socialMediaNetworkId",
			SocialMediaNetwork::getSocialMediaNetworkId);
		attributeSetterBiConsumers.put(
			"socialMediaNetworkId",
			(BiConsumer<SocialMediaNetwork, Long>)
				SocialMediaNetwork::setSocialMediaNetworkId);
		attributeGetterFunctions.put("groupId", SocialMediaNetwork::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SocialMediaNetwork, Long>)
				SocialMediaNetwork::setGroupId);
		attributeGetterFunctions.put(
			"companyId", SocialMediaNetwork::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SocialMediaNetwork, Long>)
				SocialMediaNetwork::setCompanyId);
		attributeGetterFunctions.put("name", SocialMediaNetwork::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<SocialMediaNetwork, String>)
				SocialMediaNetwork::setName);
		attributeGetterFunctions.put("logo", SocialMediaNetwork::getLogo);
		attributeSetterBiConsumers.put(
			"logo",
			(BiConsumer<SocialMediaNetwork, Long>)SocialMediaNetwork::setLogo);
		attributeGetterFunctions.put("baseURL", SocialMediaNetwork::getBaseURL);
		attributeSetterBiConsumers.put(
			"baseURL",
			(BiConsumer<SocialMediaNetwork, String>)
				SocialMediaNetwork::setBaseURL);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getSocialMediaNetworkId() {
		return _socialMediaNetworkId;
	}

	@Override
	public void setSocialMediaNetworkId(long socialMediaNetworkId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_socialMediaNetworkId = socialMediaNetworkId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public long getLogo() {
		return _logo;
	}

	@Override
	public void setLogo(long logo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_logo = logo;
	}

	@JSON
	@Override
	public String getBaseURL() {
		if (_baseURL == null) {
			return "";
		}
		else {
			return _baseURL;
		}
	}

	@Override
	public void setBaseURL(String baseURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_baseURL = baseURL;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SocialMediaNetwork.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SocialMediaNetwork toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SocialMediaNetwork>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SocialMediaNetworkImpl socialMediaNetworkImpl =
			new SocialMediaNetworkImpl();

		socialMediaNetworkImpl.setUuid(getUuid());
		socialMediaNetworkImpl.setSocialMediaNetworkId(
			getSocialMediaNetworkId());
		socialMediaNetworkImpl.setGroupId(getGroupId());
		socialMediaNetworkImpl.setCompanyId(getCompanyId());
		socialMediaNetworkImpl.setName(getName());
		socialMediaNetworkImpl.setLogo(getLogo());
		socialMediaNetworkImpl.setBaseURL(getBaseURL());

		socialMediaNetworkImpl.resetOriginalValues();

		return socialMediaNetworkImpl;
	}

	@Override
	public SocialMediaNetwork cloneWithOriginalValues() {
		SocialMediaNetworkImpl socialMediaNetworkImpl =
			new SocialMediaNetworkImpl();

		socialMediaNetworkImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		socialMediaNetworkImpl.setSocialMediaNetworkId(
			this.<Long>getColumnOriginalValue("socialMediaNetworkId"));
		socialMediaNetworkImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		socialMediaNetworkImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		socialMediaNetworkImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		socialMediaNetworkImpl.setLogo(
			this.<Long>getColumnOriginalValue("logo"));
		socialMediaNetworkImpl.setBaseURL(
			this.<String>getColumnOriginalValue("baseURL"));

		return socialMediaNetworkImpl;
	}

	@Override
	public int compareTo(SocialMediaNetwork socialMediaNetwork) {
		int value = 0;

		value = getName().compareTo(socialMediaNetwork.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SocialMediaNetwork)) {
			return false;
		}

		SocialMediaNetwork socialMediaNetwork = (SocialMediaNetwork)object;

		long primaryKey = socialMediaNetwork.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SocialMediaNetwork> toCacheModel() {
		SocialMediaNetworkCacheModel socialMediaNetworkCacheModel =
			new SocialMediaNetworkCacheModel();

		socialMediaNetworkCacheModel.uuid = getUuid();

		String uuid = socialMediaNetworkCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			socialMediaNetworkCacheModel.uuid = null;
		}

		socialMediaNetworkCacheModel.socialMediaNetworkId =
			getSocialMediaNetworkId();

		socialMediaNetworkCacheModel.groupId = getGroupId();

		socialMediaNetworkCacheModel.companyId = getCompanyId();

		socialMediaNetworkCacheModel.name = getName();

		String name = socialMediaNetworkCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			socialMediaNetworkCacheModel.name = null;
		}

		socialMediaNetworkCacheModel.logo = getLogo();

		socialMediaNetworkCacheModel.baseURL = getBaseURL();

		String baseURL = socialMediaNetworkCacheModel.baseURL;

		if ((baseURL != null) && (baseURL.length() == 0)) {
			socialMediaNetworkCacheModel.baseURL = null;
		}

		return socialMediaNetworkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SocialMediaNetwork, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SocialMediaNetwork, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SocialMediaNetwork, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SocialMediaNetwork)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SocialMediaNetwork, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SocialMediaNetwork, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SocialMediaNetwork, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SocialMediaNetwork)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SocialMediaNetwork>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SocialMediaNetwork.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _socialMediaNetworkId;
	private long _groupId;
	private long _companyId;
	private String _name;
	private long _logo;
	private String _baseURL;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SocialMediaNetwork, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SocialMediaNetwork)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"socialMediaNetworkId", _socialMediaNetworkId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("logo", _logo);
		_columnOriginalValues.put("baseURL", _baseURL);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("socialMediaNetworkId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("name", 16L);

		columnBitmasks.put("logo", 32L);

		columnBitmasks.put("baseURL", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SocialMediaNetwork _escapedModel;

}