/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.uoc.mestemi.studentjob.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Offer service. Represents a row in the &quot;SJob_Offer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>edu.uoc.mestemi.studentjob.model.impl.OfferModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>edu.uoc.mestemi.studentjob.model.impl.OfferImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Offer
 * @generated
 */
@ProviderType
public interface OfferModel
	extends BaseModel<Offer>, GroupedModel, LocalizedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a offer model instance should use the {@link Offer} interface instead.
	 */

	/**
	 * Returns the primary key of this offer.
	 *
	 * @return the primary key of this offer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this offer.
	 *
	 * @param primaryKey the primary key of this offer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this offer.
	 *
	 * @return the uuid of this offer
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this offer.
	 *
	 * @param uuid the uuid of this offer
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the offer ID of this offer.
	 *
	 * @return the offer ID of this offer
	 */
	public long getOfferId();

	/**
	 * Sets the offer ID of this offer.
	 *
	 * @param offerId the offer ID of this offer
	 */
	public void setOfferId(long offerId);

	/**
	 * Returns the province ID of this offer.
	 *
	 * @return the province ID of this offer
	 */
	public long getProvinceId();

	/**
	 * Sets the province ID of this offer.
	 *
	 * @param provinceId the province ID of this offer
	 */
	public void setProvinceId(long provinceId);

	/**
	 * Returns the group ID of this offer.
	 *
	 * @return the group ID of this offer
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this offer.
	 *
	 * @param groupId the group ID of this offer
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this offer.
	 *
	 * @return the company ID of this offer
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this offer.
	 *
	 * @param companyId the company ID of this offer
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this offer.
	 *
	 * @return the user ID of this offer
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this offer.
	 *
	 * @param userId the user ID of this offer
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this offer.
	 *
	 * @return the user uuid of this offer
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this offer.
	 *
	 * @param userUuid the user uuid of this offer
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this offer.
	 *
	 * @return the user name of this offer
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this offer.
	 *
	 * @param userName the user name of this offer
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this offer.
	 *
	 * @return the create date of this offer
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this offer.
	 *
	 * @param createDate the create date of this offer
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this offer.
	 *
	 * @return the modified date of this offer
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this offer.
	 *
	 * @param modifiedDate the modified date of this offer
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this offer.
	 *
	 * @return the name of this offer
	 */
	public String getName();

	/**
	 * Returns the localized name of this offer in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this offer
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this offer in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this offer. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this offer in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this offer
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this offer in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this offer
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this offer.
	 *
	 * @return the locales and localized names of this offer
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this offer.
	 *
	 * @param name the name of this offer
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this offer in the language.
	 *
	 * @param name the localized name of this offer
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this offer in the language, and sets the default locale.
	 *
	 * @param name the localized name of this offer
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this offer from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this offer
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this offer from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this offer
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	/**
	 * Returns the preference of this offer.
	 *
	 * @return the preference of this offer
	 */
	@AutoEscape
	public String getPreference();

	/**
	 * Sets the preference of this offer.
	 *
	 * @param preference the preference of this offer
	 */
	public void setPreference(String preference);

	/**
	 * Returns the description of this offer.
	 *
	 * @return the description of this offer
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this offer in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this offer
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this offer in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this offer. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this offer in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this offer
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this offer in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this offer
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this offer.
	 *
	 * @return the locales and localized descriptions of this offer
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this offer.
	 *
	 * @param description the description of this offer
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this offer in the language.
	 *
	 * @param description the localized description of this offer
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this offer in the language, and sets the default locale.
	 *
	 * @param description the localized description of this offer
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(
		String description, Locale locale, Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this offer from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this offer
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this offer from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this offer
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Offer cloneWithOriginalValues();

}