/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.uoc.mestemi.studentjob.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import edu.uoc.mestemi.studentjob.service.persistence.UserEnrollOfferPK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserEnrollOffer service. Represents a row in the &quot;SJob_UserEnrollOffer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>edu.uoc.mestemi.studentjob.model.impl.UserEnrollOfferModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>edu.uoc.mestemi.studentjob.model.impl.UserEnrollOfferImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserEnrollOffer
 * @generated
 */
@ProviderType
public interface UserEnrollOfferModel
	extends BaseModel<UserEnrollOffer>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user enroll offer model instance should use the {@link UserEnrollOffer} interface instead.
	 */

	/**
	 * Returns the primary key of this user enroll offer.
	 *
	 * @return the primary key of this user enroll offer
	 */
	public UserEnrollOfferPK getPrimaryKey();

	/**
	 * Sets the primary key of this user enroll offer.
	 *
	 * @param primaryKey the primary key of this user enroll offer
	 */
	public void setPrimaryKey(UserEnrollOfferPK primaryKey);

	/**
	 * Returns the uuid of this user enroll offer.
	 *
	 * @return the uuid of this user enroll offer
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user enroll offer.
	 *
	 * @param uuid the uuid of this user enroll offer
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user ID of this user enroll offer.
	 *
	 * @return the user ID of this user enroll offer
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user enroll offer.
	 *
	 * @param userId the user ID of this user enroll offer
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user enroll offer.
	 *
	 * @return the user uuid of this user enroll offer
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user enroll offer.
	 *
	 * @param userUuid the user uuid of this user enroll offer
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the offer ID of this user enroll offer.
	 *
	 * @return the offer ID of this user enroll offer
	 */
	public long getOfferId();

	/**
	 * Sets the offer ID of this user enroll offer.
	 *
	 * @param offerId the offer ID of this user enroll offer
	 */
	public void setOfferId(long offerId);

	/**
	 * Returns the group ID of this user enroll offer.
	 *
	 * @return the group ID of this user enroll offer
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user enroll offer.
	 *
	 * @param groupId the group ID of this user enroll offer
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this user enroll offer.
	 *
	 * @return the company ID of this user enroll offer
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user enroll offer.
	 *
	 * @param companyId the company ID of this user enroll offer
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this user enroll offer.
	 *
	 * @return the create date of this user enroll offer
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user enroll offer.
	 *
	 * @param createDate the create date of this user enroll offer
	 */
	public void setCreateDate(Date createDate);

	@Override
	public UserEnrollOffer cloneWithOriginalValues();

}