/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.uoc.mestemi.studentjob.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import edu.uoc.mestemi.studentjob.model.DegreeArea;
import edu.uoc.mestemi.studentjob.service.DegreeAreaLocalService;
import edu.uoc.mestemi.studentjob.service.DegreeAreaLocalServiceUtil;
import edu.uoc.mestemi.studentjob.service.persistence.CompanyProfilePersistence;
import edu.uoc.mestemi.studentjob.service.persistence.DegreeAreaPersistence;
import edu.uoc.mestemi.studentjob.service.persistence.DegreePersistence;
import edu.uoc.mestemi.studentjob.service.persistence.OfferPersistence;
import edu.uoc.mestemi.studentjob.service.persistence.SocialMediaNetworkPersistence;
import edu.uoc.mestemi.studentjob.service.persistence.SocialMediaPersistence;
import edu.uoc.mestemi.studentjob.service.persistence.StudentProfilePersistence;
import edu.uoc.mestemi.studentjob.service.persistence.UserEnrollOfferPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the degree area local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link edu.uoc.mestemi.studentjob.service.impl.DegreeAreaLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see edu.uoc.mestemi.studentjob.service.impl.DegreeAreaLocalServiceImpl
 * @generated
 */
public abstract class DegreeAreaLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, DegreeAreaLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DegreeAreaLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DegreeAreaLocalServiceUtil</code>.
	 */

	/**
	 * Adds the degree area to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DegreeAreaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param degreeArea the degree area
	 * @return the degree area that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DegreeArea addDegreeArea(DegreeArea degreeArea) {
		degreeArea.setNew(true);

		return degreeAreaPersistence.update(degreeArea);
	}

	/**
	 * Creates a new degree area with the primary key. Does not add the degree area to the database.
	 *
	 * @param degreeAreaId the primary key for the new degree area
	 * @return the new degree area
	 */
	@Override
	@Transactional(enabled = false)
	public DegreeArea createDegreeArea(long degreeAreaId) {
		return degreeAreaPersistence.create(degreeAreaId);
	}

	/**
	 * Deletes the degree area with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DegreeAreaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param degreeAreaId the primary key of the degree area
	 * @return the degree area that was removed
	 * @throws PortalException if a degree area with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DegreeArea deleteDegreeArea(long degreeAreaId)
		throws PortalException {

		return degreeAreaPersistence.remove(degreeAreaId);
	}

	/**
	 * Deletes the degree area from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DegreeAreaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param degreeArea the degree area
	 * @return the degree area that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DegreeArea deleteDegreeArea(DegreeArea degreeArea) {
		return degreeAreaPersistence.remove(degreeArea);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return degreeAreaPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DegreeArea.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return degreeAreaPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>edu.uoc.mestemi.studentjob.model.impl.DegreeAreaModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return degreeAreaPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>edu.uoc.mestemi.studentjob.model.impl.DegreeAreaModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return degreeAreaPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return degreeAreaPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return degreeAreaPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DegreeArea fetchDegreeArea(long degreeAreaId) {
		return degreeAreaPersistence.fetchByPrimaryKey(degreeAreaId);
	}

	/**
	 * Returns the degree area matching the UUID and group.
	 *
	 * @param uuid the degree area's UUID
	 * @param groupId the primary key of the group
	 * @return the matching degree area, or <code>null</code> if a matching degree area could not be found
	 */
	@Override
	public DegreeArea fetchDegreeAreaByUuidAndGroupId(
		String uuid, long groupId) {

		return degreeAreaPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the degree area with the primary key.
	 *
	 * @param degreeAreaId the primary key of the degree area
	 * @return the degree area
	 * @throws PortalException if a degree area with the primary key could not be found
	 */
	@Override
	public DegreeArea getDegreeArea(long degreeAreaId) throws PortalException {
		return degreeAreaPersistence.findByPrimaryKey(degreeAreaId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(degreeAreaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DegreeArea.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("degreeAreaId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			degreeAreaLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(DegreeArea.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"degreeAreaId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(degreeAreaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DegreeArea.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("degreeAreaId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<DegreeArea>() {

				@Override
				public void performAction(DegreeArea degreeArea)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, degreeArea);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(DegreeArea.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return degreeAreaPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return degreeAreaLocalService.deleteDegreeArea(
			(DegreeArea)persistedModel);
	}

	@Override
	public BasePersistence<DegreeArea> getBasePersistence() {
		return degreeAreaPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return degreeAreaPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the degree areas matching the UUID and company.
	 *
	 * @param uuid the UUID of the degree areas
	 * @param companyId the primary key of the company
	 * @return the matching degree areas, or an empty list if no matches were found
	 */
	@Override
	public List<DegreeArea> getDegreeAreasByUuidAndCompanyId(
		String uuid, long companyId) {

		return degreeAreaPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of degree areas matching the UUID and company.
	 *
	 * @param uuid the UUID of the degree areas
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of degree areas
	 * @param end the upper bound of the range of degree areas (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching degree areas, or an empty list if no matches were found
	 */
	@Override
	public List<DegreeArea> getDegreeAreasByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<DegreeArea> orderByComparator) {

		return degreeAreaPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the degree area matching the UUID and group.
	 *
	 * @param uuid the degree area's UUID
	 * @param groupId the primary key of the group
	 * @return the matching degree area
	 * @throws PortalException if a matching degree area could not be found
	 */
	@Override
	public DegreeArea getDegreeAreaByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return degreeAreaPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the degree areas.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>edu.uoc.mestemi.studentjob.model.impl.DegreeAreaModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of degree areas
	 * @param end the upper bound of the range of degree areas (not inclusive)
	 * @return the range of degree areas
	 */
	@Override
	public List<DegreeArea> getDegreeAreas(int start, int end) {
		return degreeAreaPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of degree areas.
	 *
	 * @return the number of degree areas
	 */
	@Override
	public int getDegreeAreasCount() {
		return degreeAreaPersistence.countAll();
	}

	/**
	 * Updates the degree area in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DegreeAreaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param degreeArea the degree area
	 * @return the degree area that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DegreeArea updateDegreeArea(DegreeArea degreeArea) {
		return degreeAreaPersistence.update(degreeArea);
	}

	/**
	 */
	@Override
	public void addDegreeDegreeArea(long degreeId, long degreeAreaId) {
		degreePersistence.addDegreeArea(degreeId, degreeAreaId);
	}

	/**
	 */
	@Override
	public void addDegreeDegreeArea(long degreeId, DegreeArea degreeArea) {
		degreePersistence.addDegreeArea(degreeId, degreeArea);
	}

	/**
	 */
	@Override
	public void addDegreeDegreeAreas(long degreeId, long[] degreeAreaIds) {
		degreePersistence.addDegreeAreas(degreeId, degreeAreaIds);
	}

	/**
	 */
	@Override
	public void addDegreeDegreeAreas(
		long degreeId, List<DegreeArea> degreeAreas) {

		degreePersistence.addDegreeAreas(degreeId, degreeAreas);
	}

	/**
	 */
	@Override
	public void clearDegreeDegreeAreas(long degreeId) {
		degreePersistence.clearDegreeAreas(degreeId);
	}

	/**
	 */
	@Override
	public void deleteDegreeDegreeArea(long degreeId, long degreeAreaId) {
		degreePersistence.removeDegreeArea(degreeId, degreeAreaId);
	}

	/**
	 */
	@Override
	public void deleteDegreeDegreeArea(long degreeId, DegreeArea degreeArea) {
		degreePersistence.removeDegreeArea(degreeId, degreeArea);
	}

	/**
	 */
	@Override
	public void deleteDegreeDegreeAreas(long degreeId, long[] degreeAreaIds) {
		degreePersistence.removeDegreeAreas(degreeId, degreeAreaIds);
	}

	/**
	 */
	@Override
	public void deleteDegreeDegreeAreas(
		long degreeId, List<DegreeArea> degreeAreas) {

		degreePersistence.removeDegreeAreas(degreeId, degreeAreas);
	}

	/**
	 * Returns the degreeIds of the degrees associated with the degree area.
	 *
	 * @param degreeAreaId the degreeAreaId of the degree area
	 * @return long[] the degreeIds of degrees associated with the degree area
	 */
	@Override
	public long[] getDegreePrimaryKeys(long degreeAreaId) {
		return degreeAreaPersistence.getDegreePrimaryKeys(degreeAreaId);
	}

	/**
	 */
	@Override
	public List<DegreeArea> getDegreeDegreeAreas(long degreeId) {
		return degreeAreaPersistence.getDegreeDegreeAreas(degreeId);
	}

	/**
	 */
	@Override
	public List<DegreeArea> getDegreeDegreeAreas(
		long degreeId, int start, int end) {

		return degreeAreaPersistence.getDegreeDegreeAreas(degreeId, start, end);
	}

	/**
	 */
	@Override
	public List<DegreeArea> getDegreeDegreeAreas(
		long degreeId, int start, int end,
		OrderByComparator<DegreeArea> orderByComparator) {

		return degreeAreaPersistence.getDegreeDegreeAreas(
			degreeId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getDegreeDegreeAreasCount(long degreeId) {
		return degreePersistence.getDegreeAreasSize(degreeId);
	}

	/**
	 */
	@Override
	public boolean hasDegreeDegreeArea(long degreeId, long degreeAreaId) {
		return degreePersistence.containsDegreeArea(degreeId, degreeAreaId);
	}

	/**
	 */
	@Override
	public boolean hasDegreeDegreeAreas(long degreeId) {
		return degreePersistence.containsDegreeAreas(degreeId);
	}

	/**
	 */
	@Override
	public void setDegreeDegreeAreas(long degreeId, long[] degreeAreaIds) {
		degreePersistence.setDegreeAreas(degreeId, degreeAreaIds);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DegreeAreaLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		degreeAreaLocalService = (DegreeAreaLocalService)aopProxy;

		_setLocalServiceUtilService(degreeAreaLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DegreeAreaLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DegreeArea.class;
	}

	protected String getModelClassName() {
		return DegreeArea.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = degreeAreaPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		DegreeAreaLocalService degreeAreaLocalService) {

		try {
			Field field = DegreeAreaLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, degreeAreaLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CompanyProfilePersistence companyProfilePersistence;

	@Reference
	protected DegreePersistence degreePersistence;

	protected DegreeAreaLocalService degreeAreaLocalService;

	@Reference
	protected DegreeAreaPersistence degreeAreaPersistence;

	@Reference
	protected OfferPersistence offerPersistence;

	@Reference
	protected SocialMediaPersistence socialMediaPersistence;

	@Reference
	protected SocialMediaNetworkPersistence socialMediaNetworkPersistence;

	@Reference
	protected StudentProfilePersistence studentProfilePersistence;

	@Reference
	protected UserEnrollOfferPersistence userEnrollOfferPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}