/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.uoc.mestemi.studentjob.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import edu.uoc.mestemi.studentjob.model.Degree;
import edu.uoc.mestemi.studentjob.service.DegreeLocalService;
import edu.uoc.mestemi.studentjob.service.DegreeLocalServiceUtil;
import edu.uoc.mestemi.studentjob.service.persistence.CompanyProfilePersistence;
import edu.uoc.mestemi.studentjob.service.persistence.DegreeAreaPersistence;
import edu.uoc.mestemi.studentjob.service.persistence.DegreePersistence;
import edu.uoc.mestemi.studentjob.service.persistence.OfferPersistence;
import edu.uoc.mestemi.studentjob.service.persistence.SocialMediaNetworkPersistence;
import edu.uoc.mestemi.studentjob.service.persistence.SocialMediaPersistence;
import edu.uoc.mestemi.studentjob.service.persistence.StudentProfilePersistence;
import edu.uoc.mestemi.studentjob.service.persistence.UserEnrollOfferPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the degree local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link edu.uoc.mestemi.studentjob.service.impl.DegreeLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see edu.uoc.mestemi.studentjob.service.impl.DegreeLocalServiceImpl
 * @generated
 */
public abstract class DegreeLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, DegreeLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DegreeLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DegreeLocalServiceUtil</code>.
	 */

	/**
	 * Adds the degree to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DegreeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param degree the degree
	 * @return the degree that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Degree addDegree(Degree degree) {
		degree.setNew(true);

		return degreePersistence.update(degree);
	}

	/**
	 * Creates a new degree with the primary key. Does not add the degree to the database.
	 *
	 * @param degreeId the primary key for the new degree
	 * @return the new degree
	 */
	@Override
	@Transactional(enabled = false)
	public Degree createDegree(long degreeId) {
		return degreePersistence.create(degreeId);
	}

	/**
	 * Deletes the degree with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DegreeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param degreeId the primary key of the degree
	 * @return the degree that was removed
	 * @throws PortalException if a degree with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Degree deleteDegree(long degreeId) throws PortalException {
		return degreePersistence.remove(degreeId);
	}

	/**
	 * Deletes the degree from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DegreeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param degree the degree
	 * @return the degree that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Degree deleteDegree(Degree degree) {
		return degreePersistence.remove(degree);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return degreePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Degree.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return degreePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>edu.uoc.mestemi.studentjob.model.impl.DegreeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return degreePersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>edu.uoc.mestemi.studentjob.model.impl.DegreeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return degreePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return degreePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return degreePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Degree fetchDegree(long degreeId) {
		return degreePersistence.fetchByPrimaryKey(degreeId);
	}

	/**
	 * Returns the degree matching the UUID and group.
	 *
	 * @param uuid the degree's UUID
	 * @param groupId the primary key of the group
	 * @return the matching degree, or <code>null</code> if a matching degree could not be found
	 */
	@Override
	public Degree fetchDegreeByUuidAndGroupId(String uuid, long groupId) {
		return degreePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the degree with the primary key.
	 *
	 * @param degreeId the primary key of the degree
	 * @return the degree
	 * @throws PortalException if a degree with the primary key could not be found
	 */
	@Override
	public Degree getDegree(long degreeId) throws PortalException {
		return degreePersistence.findByPrimaryKey(degreeId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(degreeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Degree.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("degreeId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(degreeLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Degree.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("degreeId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(degreeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Degree.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("degreeId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<Degree>() {

				@Override
				public void performAction(Degree degree)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, degree);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(Degree.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return degreePersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return degreeLocalService.deleteDegree((Degree)persistedModel);
	}

	@Override
	public BasePersistence<Degree> getBasePersistence() {
		return degreePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return degreePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the degrees matching the UUID and company.
	 *
	 * @param uuid the UUID of the degrees
	 * @param companyId the primary key of the company
	 * @return the matching degrees, or an empty list if no matches were found
	 */
	@Override
	public List<Degree> getDegreesByUuidAndCompanyId(
		String uuid, long companyId) {

		return degreePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of degrees matching the UUID and company.
	 *
	 * @param uuid the UUID of the degrees
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of degrees
	 * @param end the upper bound of the range of degrees (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching degrees, or an empty list if no matches were found
	 */
	@Override
	public List<Degree> getDegreesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<Degree> orderByComparator) {

		return degreePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the degree matching the UUID and group.
	 *
	 * @param uuid the degree's UUID
	 * @param groupId the primary key of the group
	 * @return the matching degree
	 * @throws PortalException if a matching degree could not be found
	 */
	@Override
	public Degree getDegreeByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return degreePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the degrees.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>edu.uoc.mestemi.studentjob.model.impl.DegreeModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of degrees
	 * @param end the upper bound of the range of degrees (not inclusive)
	 * @return the range of degrees
	 */
	@Override
	public List<Degree> getDegrees(int start, int end) {
		return degreePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of degrees.
	 *
	 * @return the number of degrees
	 */
	@Override
	public int getDegreesCount() {
		return degreePersistence.countAll();
	}

	/**
	 * Updates the degree in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DegreeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param degree the degree
	 * @return the degree that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Degree updateDegree(Degree degree) {
		return degreePersistence.update(degree);
	}

	/**
	 */
	@Override
	public void addDegreeAreaDegree(long degreeAreaId, long degreeId) {
		degreeAreaPersistence.addDegree(degreeAreaId, degreeId);
	}

	/**
	 */
	@Override
	public void addDegreeAreaDegree(long degreeAreaId, Degree degree) {
		degreeAreaPersistence.addDegree(degreeAreaId, degree);
	}

	/**
	 */
	@Override
	public void addDegreeAreaDegrees(long degreeAreaId, long[] degreeIds) {
		degreeAreaPersistence.addDegrees(degreeAreaId, degreeIds);
	}

	/**
	 */
	@Override
	public void addDegreeAreaDegrees(long degreeAreaId, List<Degree> degrees) {
		degreeAreaPersistence.addDegrees(degreeAreaId, degrees);
	}

	/**
	 */
	@Override
	public void clearDegreeAreaDegrees(long degreeAreaId) {
		degreeAreaPersistence.clearDegrees(degreeAreaId);
	}

	/**
	 */
	@Override
	public void deleteDegreeAreaDegree(long degreeAreaId, long degreeId) {
		degreeAreaPersistence.removeDegree(degreeAreaId, degreeId);
	}

	/**
	 */
	@Override
	public void deleteDegreeAreaDegree(long degreeAreaId, Degree degree) {
		degreeAreaPersistence.removeDegree(degreeAreaId, degree);
	}

	/**
	 */
	@Override
	public void deleteDegreeAreaDegrees(long degreeAreaId, long[] degreeIds) {
		degreeAreaPersistence.removeDegrees(degreeAreaId, degreeIds);
	}

	/**
	 */
	@Override
	public void deleteDegreeAreaDegrees(
		long degreeAreaId, List<Degree> degrees) {

		degreeAreaPersistence.removeDegrees(degreeAreaId, degrees);
	}

	/**
	 * Returns the degreeAreaIds of the degree areas associated with the degree.
	 *
	 * @param degreeId the degreeId of the degree
	 * @return long[] the degreeAreaIds of degree areas associated with the degree
	 */
	@Override
	public long[] getDegreeAreaPrimaryKeys(long degreeId) {
		return degreePersistence.getDegreeAreaPrimaryKeys(degreeId);
	}

	/**
	 */
	@Override
	public List<Degree> getDegreeAreaDegrees(long degreeAreaId) {
		return degreePersistence.getDegreeAreaDegrees(degreeAreaId);
	}

	/**
	 */
	@Override
	public List<Degree> getDegreeAreaDegrees(
		long degreeAreaId, int start, int end) {

		return degreePersistence.getDegreeAreaDegrees(degreeAreaId, start, end);
	}

	/**
	 */
	@Override
	public List<Degree> getDegreeAreaDegrees(
		long degreeAreaId, int start, int end,
		OrderByComparator<Degree> orderByComparator) {

		return degreePersistence.getDegreeAreaDegrees(
			degreeAreaId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getDegreeAreaDegreesCount(long degreeAreaId) {
		return degreeAreaPersistence.getDegreesSize(degreeAreaId);
	}

	/**
	 */
	@Override
	public boolean hasDegreeAreaDegree(long degreeAreaId, long degreeId) {
		return degreeAreaPersistence.containsDegree(degreeAreaId, degreeId);
	}

	/**
	 */
	@Override
	public boolean hasDegreeAreaDegrees(long degreeAreaId) {
		return degreeAreaPersistence.containsDegrees(degreeAreaId);
	}

	/**
	 */
	@Override
	public void setDegreeAreaDegrees(long degreeAreaId, long[] degreeIds) {
		degreeAreaPersistence.setDegrees(degreeAreaId, degreeIds);
	}

	/**
	 */
	@Override
	public void addStudentProfileDegree(long studentProfileId, long degreeId) {
		studentProfilePersistence.addDegree(studentProfileId, degreeId);
	}

	/**
	 */
	@Override
	public void addStudentProfileDegree(long studentProfileId, Degree degree) {
		studentProfilePersistence.addDegree(studentProfileId, degree);
	}

	/**
	 */
	@Override
	public void addStudentProfileDegrees(
		long studentProfileId, long[] degreeIds) {

		studentProfilePersistence.addDegrees(studentProfileId, degreeIds);
	}

	/**
	 */
	@Override
	public void addStudentProfileDegrees(
		long studentProfileId, List<Degree> degrees) {

		studentProfilePersistence.addDegrees(studentProfileId, degrees);
	}

	/**
	 */
	@Override
	public void clearStudentProfileDegrees(long studentProfileId) {
		studentProfilePersistence.clearDegrees(studentProfileId);
	}

	/**
	 */
	@Override
	public void deleteStudentProfileDegree(
		long studentProfileId, long degreeId) {

		studentProfilePersistence.removeDegree(studentProfileId, degreeId);
	}

	/**
	 */
	@Override
	public void deleteStudentProfileDegree(
		long studentProfileId, Degree degree) {

		studentProfilePersistence.removeDegree(studentProfileId, degree);
	}

	/**
	 */
	@Override
	public void deleteStudentProfileDegrees(
		long studentProfileId, long[] degreeIds) {

		studentProfilePersistence.removeDegrees(studentProfileId, degreeIds);
	}

	/**
	 */
	@Override
	public void deleteStudentProfileDegrees(
		long studentProfileId, List<Degree> degrees) {

		studentProfilePersistence.removeDegrees(studentProfileId, degrees);
	}

	/**
	 * Returns the studentProfileIds of the student profiles associated with the degree.
	 *
	 * @param degreeId the degreeId of the degree
	 * @return long[] the studentProfileIds of student profiles associated with the degree
	 */
	@Override
	public long[] getStudentProfilePrimaryKeys(long degreeId) {
		return degreePersistence.getStudentProfilePrimaryKeys(degreeId);
	}

	/**
	 */
	@Override
	public List<Degree> getStudentProfileDegrees(long studentProfileId) {
		return degreePersistence.getStudentProfileDegrees(studentProfileId);
	}

	/**
	 */
	@Override
	public List<Degree> getStudentProfileDegrees(
		long studentProfileId, int start, int end) {

		return degreePersistence.getStudentProfileDegrees(
			studentProfileId, start, end);
	}

	/**
	 */
	@Override
	public List<Degree> getStudentProfileDegrees(
		long studentProfileId, int start, int end,
		OrderByComparator<Degree> orderByComparator) {

		return degreePersistence.getStudentProfileDegrees(
			studentProfileId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getStudentProfileDegreesCount(long studentProfileId) {
		return studentProfilePersistence.getDegreesSize(studentProfileId);
	}

	/**
	 */
	@Override
	public boolean hasStudentProfileDegree(
		long studentProfileId, long degreeId) {

		return studentProfilePersistence.containsDegree(
			studentProfileId, degreeId);
	}

	/**
	 */
	@Override
	public boolean hasStudentProfileDegrees(long studentProfileId) {
		return studentProfilePersistence.containsDegrees(studentProfileId);
	}

	/**
	 */
	@Override
	public void setStudentProfileDegrees(
		long studentProfileId, long[] degreeIds) {

		studentProfilePersistence.setDegrees(studentProfileId, degreeIds);
	}

	/**
	 */
	@Override
	public void addOfferDegree(long offerId, long degreeId) {
		offerPersistence.addDegree(offerId, degreeId);
	}

	/**
	 */
	@Override
	public void addOfferDegree(long offerId, Degree degree) {
		offerPersistence.addDegree(offerId, degree);
	}

	/**
	 */
	@Override
	public void addOfferDegrees(long offerId, long[] degreeIds) {
		offerPersistence.addDegrees(offerId, degreeIds);
	}

	/**
	 */
	@Override
	public void addOfferDegrees(long offerId, List<Degree> degrees) {
		offerPersistence.addDegrees(offerId, degrees);
	}

	/**
	 */
	@Override
	public void clearOfferDegrees(long offerId) {
		offerPersistence.clearDegrees(offerId);
	}

	/**
	 */
	@Override
	public void deleteOfferDegree(long offerId, long degreeId) {
		offerPersistence.removeDegree(offerId, degreeId);
	}

	/**
	 */
	@Override
	public void deleteOfferDegree(long offerId, Degree degree) {
		offerPersistence.removeDegree(offerId, degree);
	}

	/**
	 */
	@Override
	public void deleteOfferDegrees(long offerId, long[] degreeIds) {
		offerPersistence.removeDegrees(offerId, degreeIds);
	}

	/**
	 */
	@Override
	public void deleteOfferDegrees(long offerId, List<Degree> degrees) {
		offerPersistence.removeDegrees(offerId, degrees);
	}

	/**
	 * Returns the offerIds of the offers associated with the degree.
	 *
	 * @param degreeId the degreeId of the degree
	 * @return long[] the offerIds of offers associated with the degree
	 */
	@Override
	public long[] getOfferPrimaryKeys(long degreeId) {
		return degreePersistence.getOfferPrimaryKeys(degreeId);
	}

	/**
	 */
	@Override
	public List<Degree> getOfferDegrees(long offerId) {
		return degreePersistence.getOfferDegrees(offerId);
	}

	/**
	 */
	@Override
	public List<Degree> getOfferDegrees(long offerId, int start, int end) {
		return degreePersistence.getOfferDegrees(offerId, start, end);
	}

	/**
	 */
	@Override
	public List<Degree> getOfferDegrees(
		long offerId, int start, int end,
		OrderByComparator<Degree> orderByComparator) {

		return degreePersistence.getOfferDegrees(
			offerId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getOfferDegreesCount(long offerId) {
		return offerPersistence.getDegreesSize(offerId);
	}

	/**
	 */
	@Override
	public boolean hasOfferDegree(long offerId, long degreeId) {
		return offerPersistence.containsDegree(offerId, degreeId);
	}

	/**
	 */
	@Override
	public boolean hasOfferDegrees(long offerId) {
		return offerPersistence.containsDegrees(offerId);
	}

	/**
	 */
	@Override
	public void setOfferDegrees(long offerId, long[] degreeIds) {
		offerPersistence.setDegrees(offerId, degreeIds);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DegreeLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		degreeLocalService = (DegreeLocalService)aopProxy;

		_setLocalServiceUtilService(degreeLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DegreeLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Degree.class;
	}

	protected String getModelClassName() {
		return Degree.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = degreePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		DegreeLocalService degreeLocalService) {

		try {
			Field field = DegreeLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, degreeLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CompanyProfilePersistence companyProfilePersistence;

	protected DegreeLocalService degreeLocalService;

	@Reference
	protected DegreePersistence degreePersistence;

	@Reference
	protected DegreeAreaPersistence degreeAreaPersistence;

	@Reference
	protected OfferPersistence offerPersistence;

	@Reference
	protected SocialMediaPersistence socialMediaPersistence;

	@Reference
	protected SocialMediaNetworkPersistence socialMediaNetworkPersistence;

	@Reference
	protected StudentProfilePersistence studentProfilePersistence;

	@Reference
	protected UserEnrollOfferPersistence userEnrollOfferPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}