/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.uoc.mestemi.studentjob.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import edu.uoc.mestemi.studentjob.model.SocialMediaNetwork;
import edu.uoc.mestemi.studentjob.service.SocialMediaNetworkLocalService;
import edu.uoc.mestemi.studentjob.service.SocialMediaNetworkLocalServiceUtil;
import edu.uoc.mestemi.studentjob.service.persistence.CompanyProfilePersistence;
import edu.uoc.mestemi.studentjob.service.persistence.DegreeAreaPersistence;
import edu.uoc.mestemi.studentjob.service.persistence.DegreePersistence;
import edu.uoc.mestemi.studentjob.service.persistence.OfferPersistence;
import edu.uoc.mestemi.studentjob.service.persistence.SocialMediaNetworkPersistence;
import edu.uoc.mestemi.studentjob.service.persistence.SocialMediaPersistence;
import edu.uoc.mestemi.studentjob.service.persistence.StudentProfilePersistence;
import edu.uoc.mestemi.studentjob.service.persistence.UserEnrollOfferPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the social media network local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link edu.uoc.mestemi.studentjob.service.impl.SocialMediaNetworkLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see edu.uoc.mestemi.studentjob.service.impl.SocialMediaNetworkLocalServiceImpl
 * @generated
 */
public abstract class SocialMediaNetworkLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   SocialMediaNetworkLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SocialMediaNetworkLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>SocialMediaNetworkLocalServiceUtil</code>.
	 */

	/**
	 * Adds the social media network to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SocialMediaNetworkLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param socialMediaNetwork the social media network
	 * @return the social media network that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SocialMediaNetwork addSocialMediaNetwork(
		SocialMediaNetwork socialMediaNetwork) {

		socialMediaNetwork.setNew(true);

		return socialMediaNetworkPersistence.update(socialMediaNetwork);
	}

	/**
	 * Creates a new social media network with the primary key. Does not add the social media network to the database.
	 *
	 * @param socialMediaNetworkId the primary key for the new social media network
	 * @return the new social media network
	 */
	@Override
	@Transactional(enabled = false)
	public SocialMediaNetwork createSocialMediaNetwork(
		long socialMediaNetworkId) {

		return socialMediaNetworkPersistence.create(socialMediaNetworkId);
	}

	/**
	 * Deletes the social media network with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SocialMediaNetworkLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param socialMediaNetworkId the primary key of the social media network
	 * @return the social media network that was removed
	 * @throws PortalException if a social media network with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SocialMediaNetwork deleteSocialMediaNetwork(
			long socialMediaNetworkId)
		throws PortalException {

		return socialMediaNetworkPersistence.remove(socialMediaNetworkId);
	}

	/**
	 * Deletes the social media network from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SocialMediaNetworkLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param socialMediaNetwork the social media network
	 * @return the social media network that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SocialMediaNetwork deleteSocialMediaNetwork(
		SocialMediaNetwork socialMediaNetwork) {

		return socialMediaNetworkPersistence.remove(socialMediaNetwork);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return socialMediaNetworkPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			SocialMediaNetwork.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return socialMediaNetworkPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>edu.uoc.mestemi.studentjob.model.impl.SocialMediaNetworkModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return socialMediaNetworkPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>edu.uoc.mestemi.studentjob.model.impl.SocialMediaNetworkModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return socialMediaNetworkPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return socialMediaNetworkPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return socialMediaNetworkPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public SocialMediaNetwork fetchSocialMediaNetwork(
		long socialMediaNetworkId) {

		return socialMediaNetworkPersistence.fetchByPrimaryKey(
			socialMediaNetworkId);
	}

	/**
	 * Returns the social media network matching the UUID and group.
	 *
	 * @param uuid the social media network's UUID
	 * @param groupId the primary key of the group
	 * @return the matching social media network, or <code>null</code> if a matching social media network could not be found
	 */
	@Override
	public SocialMediaNetwork fetchSocialMediaNetworkByUuidAndGroupId(
		String uuid, long groupId) {

		return socialMediaNetworkPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the social media network with the primary key.
	 *
	 * @param socialMediaNetworkId the primary key of the social media network
	 * @return the social media network
	 * @throws PortalException if a social media network with the primary key could not be found
	 */
	@Override
	public SocialMediaNetwork getSocialMediaNetwork(long socialMediaNetworkId)
		throws PortalException {

		return socialMediaNetworkPersistence.findByPrimaryKey(
			socialMediaNetworkId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			socialMediaNetworkLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SocialMediaNetwork.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"socialMediaNetworkId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			socialMediaNetworkLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(SocialMediaNetwork.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"socialMediaNetworkId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			socialMediaNetworkLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SocialMediaNetwork.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"socialMediaNetworkId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return socialMediaNetworkPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return socialMediaNetworkLocalService.deleteSocialMediaNetwork(
			(SocialMediaNetwork)persistedModel);
	}

	@Override
	public BasePersistence<SocialMediaNetwork> getBasePersistence() {
		return socialMediaNetworkPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return socialMediaNetworkPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the social media networks matching the UUID and company.
	 *
	 * @param uuid the UUID of the social media networks
	 * @param companyId the primary key of the company
	 * @return the matching social media networks, or an empty list if no matches were found
	 */
	@Override
	public List<SocialMediaNetwork> getSocialMediaNetworksByUuidAndCompanyId(
		String uuid, long companyId) {

		return socialMediaNetworkPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of social media networks matching the UUID and company.
	 *
	 * @param uuid the UUID of the social media networks
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of social media networks
	 * @param end the upper bound of the range of social media networks (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching social media networks, or an empty list if no matches were found
	 */
	@Override
	public List<SocialMediaNetwork> getSocialMediaNetworksByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<SocialMediaNetwork> orderByComparator) {

		return socialMediaNetworkPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the social media network matching the UUID and group.
	 *
	 * @param uuid the social media network's UUID
	 * @param groupId the primary key of the group
	 * @return the matching social media network
	 * @throws PortalException if a matching social media network could not be found
	 */
	@Override
	public SocialMediaNetwork getSocialMediaNetworkByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return socialMediaNetworkPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the social media networks.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>edu.uoc.mestemi.studentjob.model.impl.SocialMediaNetworkModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of social media networks
	 * @param end the upper bound of the range of social media networks (not inclusive)
	 * @return the range of social media networks
	 */
	@Override
	public List<SocialMediaNetwork> getSocialMediaNetworks(int start, int end) {
		return socialMediaNetworkPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of social media networks.
	 *
	 * @return the number of social media networks
	 */
	@Override
	public int getSocialMediaNetworksCount() {
		return socialMediaNetworkPersistence.countAll();
	}

	/**
	 * Updates the social media network in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SocialMediaNetworkLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param socialMediaNetwork the social media network
	 * @return the social media network that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SocialMediaNetwork updateSocialMediaNetwork(
		SocialMediaNetwork socialMediaNetwork) {

		return socialMediaNetworkPersistence.update(socialMediaNetwork);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SocialMediaNetworkLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		socialMediaNetworkLocalService =
			(SocialMediaNetworkLocalService)aopProxy;

		_setLocalServiceUtilService(socialMediaNetworkLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SocialMediaNetworkLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SocialMediaNetwork.class;
	}

	protected String getModelClassName() {
		return SocialMediaNetwork.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				socialMediaNetworkPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		SocialMediaNetworkLocalService socialMediaNetworkLocalService) {

		try {
			Field field =
				SocialMediaNetworkLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, socialMediaNetworkLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CompanyProfilePersistence companyProfilePersistence;

	@Reference
	protected DegreePersistence degreePersistence;

	@Reference
	protected DegreeAreaPersistence degreeAreaPersistence;

	@Reference
	protected OfferPersistence offerPersistence;

	@Reference
	protected SocialMediaPersistence socialMediaPersistence;

	protected SocialMediaNetworkLocalService socialMediaNetworkLocalService;

	@Reference
	protected SocialMediaNetworkPersistence socialMediaNetworkPersistence;

	@Reference
	protected StudentProfilePersistence studentProfilePersistence;

	@Reference
	protected UserEnrollOfferPersistence userEnrollOfferPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}